# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# ファイルをtree表示してくれる
[[plugins]]
repo = 'scrooloose/nerdtree'

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# 入力補完
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]]
repo = 'vim-scripts/deoplete-rct'

#[[plugins]]
#repo = 'baabelfish/nvim-nim'

[[plugins]]
repo = 'wlangstroth/vim-racket'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'previm/previm'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'zah/nim.vim'

# Swift 用の設定
[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'landaire/deoplete-swift'

[[plugins]]
repo = 'kballard/vim-swift'

[[plugins]]
repo = 'keith/swift.vim'
